#!/usr/bin/env bash
# Build fpengine.bin -- SuperBasic's float engine as a loadable blob.
#
# The engine SOURCES come from the sibling checkout unchanged; what this
# script adds is glue.gen.s, four routines extracted VERBATIM from the
# portable floats.s at build time so no copy exists to drift. See
# fpengine.s for the ABI.
set -e
cd "$(dirname "$0")"

SB=../../X816_SuperBasic
[ -d "$SB/basic816/src" ] || { echo "X816_SuperBasic checkout not found beside this one"; exit 1; }

python - "$SB" <<'PY'
import io, re, sys

src = io.open(sys.argv[1] + "/basic816/src/floats.s",
              encoding="utf-8", errors="replace").read().replace("\r\n", "\n")

def proc(name):
    m = re.search(r"^" + name + r"\s+\.proc.*?^\s*\.pend", src, re.M | re.S)
    assert m, name + " not found in floats.s"
    return m.group(0)

def const(name):
    m = re.search(r"^" + name + r"\s+\.dword.*$", src, re.M)
    assert m, name + " not found in floats.s"
    return m.group(0)

parts = ["; GENERATED by build.sh from X816_SuperBasic/basic816/src/floats.s",
         "; -- do not edit; edit the original and rebuild.",
         ""]
for name in ["FARG1EQ0", "FP_COMPARE", "ITOF", "FTOI"]:
    parts.append(proc(name))
    parts.append("")
io.open("glue.gen.s", "w", encoding="utf-8", newline="\n").write("\n".join(parts))
print("glue.gen.s: %d lines" % sum(p.count("\n") + 1 for p in parts))
PY

"$SB/64tass/64tass.exe" \
    --flat -b --m65816 \
    -o fpengine.bin \
    --list=fpengine.lst --labels=fpengine.lbl \
    -I "$SB/basic816/src/X816" \
    fpengine.s

ls -la fpengine.bin
